
spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
